import { CraftCard, CatalogProduct, RawMaterial, LogisticsOrder, UserProfile, UserCart } from './types';

export const seedUsers: UserProfile[] = [
  // CUSTOMER PROFILES
  {
    id: 'user-cust-01',
    name: 'Ananya Sharma',
    email: 'ananya@client.com',
    phone: '+91 98765 43210',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-cust-02',
    name: 'Maya Kapoor',
    email: 'maya@client.com',
    phone: '+91 98200 99887',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-cust-03',
    name: 'Rhea K.',
    email: 'rhea@client.com',
    phone: '+91 99887 76655',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },

  // ARTISAN ATELIER & ADMIN PROFILES
  {
    id: 'user-admin-01',
    name: 'Nita Sharma',
    email: 'nita@dashnit.com',
    phone: '+91 98290 11223',
    role: 'atelier_manager',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-admin-02',
    name: 'Dashrath M.',
    email: 'dashrath@dashnit.com',
    phone: '+91 94140 88219',
    role: 'artisan_crafter',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-admin-03',
    name: 'Kavita S.',
    email: 'kavita@dashnit.com',
    phone: '+91 98765 11234',
    role: 'qc_packaging',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-admin-04',
    name: 'Ramesh Patel',
    email: 'ramesh@dashnit.com',
    phone: '+91 98200 44556',
    role: 'logistics_dispatcher',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
];

export const initialCarts: UserCart[] = [
  {
    userId: 'user-cust-01',
    customerName: 'Ananya Sharma',
    customerPhone: '+91 98765 43210',
    subtotal: 2348,
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    items: [
      {
        id: 'cart-item-1',
        productId: 'prod-01',
        sku: 'DN-CAN-001',
        title: 'Bespoke Soy Candle (French Lavender & Cedarwood)',
        price: 849,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
        category: 'candle',
        fulfillmentMode: 'made_to_order',
        customDetails: 'Wood Wick • Inscription: "Happy 25th Maya!"',
      },
      {
        id: 'cart-item-2',
        productId: 'prod-02',
        sku: 'DN-CRO-001',
        title: 'Handcrafted Daisy Motif Tote Bag',
        price: 1499,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
        category: 'crochet',
        fulfillmentMode: 'made_to_order',
        customDetails: 'Yarn: Sage + Buttercup • Monogram "A.S."',
      },
    ],
  },
  {
    userId: 'user-cust-02',
    customerName: 'Maya Kapoor',
    customerPhone: '+91 98200 99887',
    subtotal: 949,
    updatedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    items: [
      {
        id: 'cart-item-3',
        productId: 'prod-03',
        sku: 'DN-CAN-003',
        title: 'Triple-Wick Bubble Candle (Warm Cashmere Vanilla)',
        price: 949,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1602874801007-bd458bb1b8b8?w=600&auto=format&fit=crop&q=80',
        category: 'candle',
        fulfillmentMode: 'ready_to_ship',
      },
    ],
  },
];

export const mockCatalogProducts: CatalogProduct[] = [
  {
    id: 'prod-01',
    sku: 'DN-CAN-001',
    title: 'Bespoke Soy Candle Jar',
    subtitle: 'French Lavender & Himalayan Cedarwood • Crackling Wood Wick',
    category: 'candle',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608181831558-5d3a5a73e51a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572726729437-3732efc8ec8b?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Hand-poured in small artisanal batches in Jaipur using 100% pure soy wax, infused with therapeutic French lavender and earthy cedarwood essential oils. Features a soothing crackling rosewood wick.',
    fragranceNotes: {
      top: 'French High-Altitude Lavender & Bergamot Peel',
      middle: 'Crushed Clary Sage & Chamomile Blossom',
      base: 'Himalayan Cedarwood, Amber & Sandalwood Bark',
    },
    burnTimeHours: 48,
    dimensions: '8.5 cm (D) x 10.2 cm (H) • 240g Wax Net Wt.',
    materials: '100% Golden Wax 464, Rosewood Wick, Heavy Apothecary Amber Glass',
    careInstructions:
      'Trim wooden wick to 1/8 inch before every burn. Allow initial melt pool to reach glass edges (approx 2 hrs) to prevent tunneling.',
    craftMedium: 'Soy Wax & Botanicals',
    fulfillmentMode: 'ready_to_ship',
    stockCount: 28,
    leadTimeBuffer: 'Same-day pack (Ready to Ship)',
    mrp: 999,
    salePrice: 849,
    gstRate: '12% GST',
    minReserve: 10,
    criticalLow: false,
    statusText: 'Batch #JA-2401 cured & ready',
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    id: 'prod-02',
    sku: 'DN-CRO-001',
    title: 'Custom Daisy Motif Tote Bag',
    subtitle: '100% Organic Spun Combed Cotton • Bespoke Dual Colorway',
    category: 'crochet',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'An iconic DashNit heirloom tote meticulously crocheted with 14 individual granny squares featuring three-dimensional daisy motifs. Reinforced double-crochet handles withstand daily laptop & book carry.',
    dimensions: '38 cm (W) x 42 cm (H) • 28 cm Strap Drop',
    materials: '100% GOTS-Certified 4-Ply Organic Combed Cotton Yarn',
    careInstructions: 'Hand wash gently in cool water with mild wool detergent. Dry flat in shade to preserve stitch tension.',
    craftMedium: '4-Ply Organic Cotton',
    fulfillmentMode: 'made_to_order',
    stockCount: 0,
    crafterAssigned: 'Ritu Devi & Nita S.',
    leadTimeBuffer: '3-4 business days crafting',
    mrp: 1799,
    salePrice: 1499,
    gstRate: '5% GST',
    minReserve: 0,
    statusText: 'Made-to-Order commission',
    rating: 4.95,
    reviewsCount: 24,
  },
  {
    id: 'prod-03',
    sku: 'DN-CAN-002',
    title: 'Royal Mysore Sandalwood & Amber Jar',
    subtitle: 'Single Egyptian Cotton Wick • Frosted Matte White Vessel',
    category: 'candle',
    image: 'https://images.unsplash.com/photo-1572726729437-3732efc8ec8b?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1572726729437-3732efc8ec8b?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Warm and grounding sacred Sandalwood from Mysore paired with golden resinous Amber and delicate saffron. Creates a tranquil temple sanctuary atmosphere for evening meditation.',
    fragranceNotes: {
      top: 'Kashmiri Saffron & Cardamom Pod',
      middle: 'Mysore Sandalwood & Sweet Jasmine Sambac',
      base: 'Golden Amber Resin, Vanilla Pod & Smoked Musk',
    },
    burnTimeHours: 52,
    dimensions: '9.0 cm (D) x 11.0 cm (H) • 280g Wax Net Wt.',
    materials: 'Soy-Coconut Wax Blend, Braided Lead-free Cotton Wick, Matte Ceramic Vessel',
    careInstructions: 'Do not burn for more than 4 consecutive hours. Keep away from drafts.',
    craftMedium: 'Soy Wax & Wood Wick',
    fulfillmentMode: 'ready_to_ship',
    stockCount: 3,
    leadTimeBuffer: 'Same-day dispatch',
    mrp: 1299,
    salePrice: 1150,
    gstRate: '12% GST',
    minReserve: 8,
    criticalLow: true,
    statusText: 'Critical Low • Batch pour recommended',
    rating: 4.88,
    reviewsCount: 19,
  },
  {
    id: 'prod-04',
    sku: 'DN-CAN-003',
    title: 'Triple-Wick Bubble Pillar Candle',
    subtitle: 'Sculptural Bubble Sphere • Madagascar Vanilla Bean & Cashmere',
    category: 'candle',
    image: 'https://images.unsplash.com/photo-1602874801007-bd458bb1b8b8?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1602874801007-bd458bb1b8b8?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'A stunning sculptural statement piece for coffee tables and nightstands. Poured in our signature pillared bubble mold with warm comforting vanilla and cashmere aroma.',
    fragranceNotes: {
      top: 'Warm Whipped Cream & Spiced Nutmeg',
      middle: 'Madagascar Vanilla Orchid',
      base: 'Cashmere Musk, Tonka Bean & Benzoin',
    },
    burnTimeHours: 36,
    dimensions: '8.0 cm x 8.0 cm x 8.0 cm Cube • 180g',
    materials: '100% Hard Pour Natural Soy Pillar Wax',
    careInstructions: 'Always burn on a heat-safe ceramic or stone coaster to catch pillar wax drips.',
    craftMedium: 'Soy Pillar Wax',
    fulfillmentMode: 'ready_to_ship',
    stockCount: 14,
    leadTimeBuffer: 'Same-day pack',
    mrp: 1099,
    salePrice: 949,
    gstRate: '12% GST',
    minReserve: 5,
    criticalLow: false,
    statusText: 'In Stock • Studio Locker B4',
    rating: 4.75,
    reviewsCount: 42,
  },
  {
    id: 'prod-05',
    sku: 'DN-CRO-002',
    title: 'Cozy Waffle Crochet Throw Blanket',
    subtitle: 'Terracotta & Oatmeal Blend • Hand-Stitched Organic Combed Cotton',
    category: 'crochet',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'A deeply tactile, weighted throw blanket worked in intricate waffle crochet stitch that traps warm air pockets. An heirloom living room accent piece.',
    dimensions: '120 cm x 150 cm • 1.4 kg',
    materials: '100% Organic Spun Combed Cotton Yarn (Double Strand)',
    careInstructions: 'Machine washable on gentle wool cycle with cold water. Dry flat.',
    craftMedium: 'Combed Cotton Yarn',
    fulfillmentMode: 'made_to_order',
    stockCount: 0,
    crafterAssigned: 'Dashrath M.',
    leadTimeBuffer: '5-7 business days crafting',
    mrp: 3800,
    salePrice: 3200,
    gstRate: '5% GST',
    minReserve: 0,
    statusText: '1 commission in crafting',
    rating: 5.0,
    reviewsCount: 9,
  },
  {
    id: 'prod-06',
    sku: 'DN-BOX-001',
    title: 'Signature Eco-Luxe Gift Box',
    subtitle: 'Hand-poured Soy Candle + 4x Crochet Coasters + Calligraphy Card',
    category: 'gift_box',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'The quintessential celebratory gift hamper. Contains 1 amber soy jar candle of choice, 4 matching botanical crochet mug rugs, and a bespoke handwritten message card sealed with gold beeswax.',
    dimensions: '26 cm (L) x 20 cm (W) x 12 cm (H) • 840g Gross Wt.',
    materials: 'Recycled Kraft Rigid Box, Mulberry Paper, Satin Ribbon, Wax Seal',
    craftMedium: 'Mixed Artisan Curated',
    fulfillmentMode: 'hybrid',
    stockCount: 18,
    leadTimeBuffer: '24-48 hours bespoke packing',
    mrp: 2799,
    salePrice: 2450,
    gstRate: '12% GST',
    minReserve: 5,
    criticalLow: false,
    statusText: 'Ready to manifest',
    rating: 4.96,
    reviewsCount: 51,
  },
  {
    id: 'prod-07',
    sku: 'DN-MELT-001',
    title: 'Botanical Soy Wax Melt Box',
    subtitle: 'Rose Petals, French Lavender & Royal Sandalwood (Pack of 12)',
    category: 'wax_melt',
    image: 'https://images.unsplash.com/photo-1603006905393-c6c7476e3d23?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1603006905393-c6c7476e3d23?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Flameless room fragrance melts cast with dried botanical blossoms. Simply pop 2 squares into a ceramic aroma diffuser or electric burner for instant fragrance throw.',
    fragranceNotes: {
      top: 'Damascena Rose Petal & Bergamot',
      middle: 'Wild Lavender Bud',
      base: 'Golden Amber & Sandalwood',
    },
    burnTimeHours: 72,
    dimensions: '14 cm x 10 cm Box • 160g Net Wt.',
    materials: 'Pure Soy Wax, Botanical Flora, Essential Fragrance Extracts',
    craftMedium: 'Natural Soy Wax',
    fulfillmentMode: 'ready_to_ship',
    stockCount: 35,
    leadTimeBuffer: 'Immediate dispatch',
    mrp: 599,
    salePrice: 499,
    gstRate: '12% GST',
    minReserve: 10,
    criticalLow: false,
    statusText: 'Lot #29A available',
    rating: 4.8,
    reviewsCount: 31,
  },
  {
    id: 'prod-08',
    sku: 'DN-CRO-003',
    title: 'Pastel Meadow Bunny Amigurumi',
    subtitle: 'Sky Blue Cotton • Safety Eyes • Hypoallergenic Cloud Stuffing',
    category: 'crochet',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    ],
    description:
      'Charming handmade amigurumi soft toy for babies and nurseries. Tight stitch density prevents filling leakage. Includes custom embroidered name tag on ear.',
    dimensions: '22 cm (H) x 12 cm (W) • 120g',
    materials: '100% Combed Cotton Yarn, EN71 Safety Lock Eyes, Recycled Polyfill',
    careInstructions: 'Spot clean with damp cloth. Hand washable in baby-safe soap.',
    craftMedium: 'Amigurumi Crochet',
    fulfillmentMode: 'made_to_order',
    stockCount: 0,
    crafterAssigned: 'Dashrath M.',
    leadTimeBuffer: '2 business days',
    mrp: 1399,
    salePrice: 1199,
    gstRate: '5% GST',
    minReserve: 0,
    statusText: 'Custom commission',
    rating: 5.0,
    reviewsCount: 16,
  },
];

export const initialCraftCards: CraftCard[] = [
  // STAGE 01: NEW PLACED
  {
    id: 'DN-1048',
    stage: 'new_placed',
    title: 'Bespoke Soy Candle Jar',
    subtitle: 'Amber Glass • Crackling Wood Wick',
    type: 'candle',
    urgent: true,
    customerName: 'Ananya S.',
    customerPhone: '+91 98765 43210',
    dueText: 'Due: in 3 days',
    price: 849,
    paymentMethod: 'UPI Intent (GPay)',
    paymentStatus: 'Captured',
    details: {
      scent: 'French Lavender & Cedar',
      vinylInscription: '“Happy 25th Maya!”',
      fastTrack: true,
      giftNote: 'Happy Birthday Maya! Wishing you boundless joy and gentle warmth always.',
      destination: 'Bangalore, KA 560001',
    },
  },
  {
    id: 'DN-1050',
    stage: 'new_placed',
    title: 'Custom Daisy Tote Bag',
    subtitle: '100% Organic Spun Cotton',
    type: 'crochet',
    tag: 'Crochet MTO',
    customerName: 'Rhea K.',
    customerPhone: '+91 99887 76655',
    dueText: 'Lead: 5 days',
    price: 1499,
    paymentMethod: 'RuPay Card',
    paymentStatus: 'Pre-Authorized',
    details: {
      yarnPalette: [
        { name: 'Sage', hex: '#8EA885' },
        { name: 'Buttercup', hex: '#F4D35E' },
      ],
      monogram: '‘A.R.’ (Pocket Rim)',
      destination: 'Mumbai, MH 400050',
    },
  },
  {
    id: 'DN-1053',
    stage: 'new_placed',
    title: 'Botanical Wax Melt Set',
    subtitle: 'Rose Petals & Sandalwood',
    type: 'wax_melt',
    tag: 'RTS Ready',
    customerName: 'Pooja T.',
    customerPhone: '+91 91234 56789',
    dueText: 'Same-day pack',
    price: 499,
    paymentMethod: 'PhonePe UPI',
    paymentStatus: 'Captured',
    details: {
      stockLot: 'In-Stock Lot #29A',
      fastTrack: true,
      destination: 'Jaipur Local Hub',
    },
  },

  // STAGE 02: IN CRAFTING
  {
    id: 'DN-1044',
    stage: 'in_crafting',
    title: 'Cozy Waffle Crochet Throw',
    subtitle: 'Terracotta & Oatmeal Blend • Size M',
    type: 'crochet',
    tag: 'Crochet Room',
    urgent: true,
    customerName: 'Aarav V.',
    customerPhone: '+91 94140 88219',
    dueText: 'Due Tomorrow',
    price: 3200,
    paymentMethod: 'HDFC NetBanking',
    paymentStatus: 'Captured',
    details: {
      stitchProgress: { percent: 65, label: '65% (Row 42/65)' },
      artisan: 'Dashrath M.',
      destination: 'New Delhi 110024',
    },
  },
  {
    id: 'DN-1047',
    stage: 'in_crafting',
    title: 'Triple-Wick Bubble Candle',
    subtitle: 'Vanilla Bean & Cashmere Wax',
    type: 'candle',
    tag: 'Curing Phase',
    customerName: 'Simran B.',
    customerPhone: '+91 97722 11004',
    dueText: '30h remaining',
    price: 949,
    paymentMethod: 'Paytm UPI',
    paymentStatus: 'Captured',
    details: {
      curing: {
        pouredAgo: '18h ago',
        remaining: '30h remaining',
        percent: 37,
        roomTemp: 'Hold in dark temperature room (21°C)',
      },
      artisan: 'Nita S.',
      locker: 'Locker #B-4',
      destination: 'Hyderabad, TS 500034',
    },
  },

  // STAGE 03: QC & PACKAGING
  {
    id: 'DN-1039',
    stage: 'qc_packaging',
    title: 'Signature Eco-Luxe Box',
    subtitle: '4x Coasters + Cinnamon Candle Bundle',
    type: 'gift_hamper',
    tag: 'QC PASSED',
    customerName: 'Vikram Mehta',
    customerPhone: '+91 98450 12345',
    dueText: 'Ready to Manifest',
    price: 2450,
    paymentMethod: 'Mastercard',
    paymentStatus: 'Captured',
    details: {
      qcPassed: true,
      qcChecks: [
        'Wick Centered & Wax Burn Level Tested',
        'Yarn Weave Tension Verified (Grade A)',
        'Handwritten Wax Seal Card Attached',
      ],
      weightGrams: 840,
      boxSize: 'Box 03 (Medium Kraft)',
      destination: 'Chennai, TN 600004',
    },
  },

  // STAGE 04: MANIFESTED
  {
    id: 'DN-1035',
    stage: 'manifested',
    title: 'Custom Monogram Scarf & Jar',
    subtitle: 'Delhivery Direct #DL-883920194',
    type: 'gift_hamper',
    customerName: 'Meera Iyer',
    customerPhone: '+91 98200 99887',
    dueText: 'In Transit',
    price: 1899,
    paymentMethod: 'UPI Intent (PhonePe)',
    paymentStatus: 'Captured',
    details: {
      courier: 'Delhivery Direct',
      awb: '#DL-883920194',
      courierStatus: 'Picked up by Jaipur Courier Hub',
      destination: 'Dest: Mumbai South',
      whatsappAlertSent: '14:22',
    },
  },
];

export const mockRawMaterials: RawMaterial[] = [
  {
    id: 'rm-01',
    name: 'Pure Soy Wax Flakes (Golden Wax 464)',
    sku: 'RAW-WAX-01',
    batchInfo: 'Lot #GW-882 (Origin: USA)',
    stockLevel: 14.5,
    unit: 'kg',
    threshold: 20.0,
    status: 'critical',
    supplier: 'Rajasthan Wax & Petrochem',
    estimateCost: 380,
    standardOrderQty: '50 kg Bag',
    note: 'PO Sent via WhatsApp (100 kg)',
  },
  {
    id: 'rm-02',
    name: 'French High-Altitude Lavender Oil',
    sku: 'RAW-OIL-02',
    batchInfo: 'Extraction: 2026-06 (IFRA Certified)',
    stockLevel: 450,
    unit: 'ml',
    threshold: 500,
    status: 'low',
    supplier: 'Kashmir Botanical Distillers',
    estimateCost: 4.5,
    standardOrderQty: '1000 ml Bottle',
  },
  {
    id: 'rm-03',
    name: 'Crackling Rosewood Wicks (13mm)',
    sku: 'RAW-WICK-03',
    batchInfo: 'Pack of 100 with metal clips',
    stockLevel: 68,
    unit: 'pcs',
    threshold: 100,
    status: 'low',
    supplier: 'Delhi Candle Supplies Ltd.',
    estimateCost: 8.5,
    standardOrderQty: '500 pcs Pack',
  },
  {
    id: 'rm-04',
    name: '4-Ply Organic Combed Cotton (Sage)',
    sku: 'RAW-YARN-04',
    batchInfo: 'GOTS Certified • Lot #SG-401',
    stockLevel: 18,
    unit: 'skeins',
    threshold: 10,
    status: 'normal',
    supplier: 'Coimbatore Organic Mills',
    estimateCost: 145,
    standardOrderQty: '50 Skein Box',
  },
  {
    id: 'rm-05',
    name: '4-Ply Organic Combed Cotton (Buttercup)',
    sku: 'RAW-YARN-05',
    batchInfo: 'GOTS Certified • Lot #BC-308',
    stockLevel: 12,
    unit: 'skeins',
    threshold: 10,
    status: 'normal',
    supplier: 'Coimbatore Organic Mills',
    estimateCost: 145,
    standardOrderQty: '50 Skein Box',
  },
];

export const mockLogisticsOrders: LogisticsOrder[] = [
  {
    orderId: 'DN-1035',
    customerName: 'Meera Iyer',
    phone: '+91 98200 99887',
    address: 'B-402, Sea View Towers, Worli Sea Face',
    city: 'Mumbai',
    state: 'Maharashtra',
    pinCode: '400018',
    date: 'Today, 11:30 AM',
    amount: 1899,
    paymentMethod: 'UPI Intent (PhonePe)',
    paymentStatus: 'PAID (Verified)',
    status: 'manifested',
    statusBadge: 'MANIFESTED',
    items: [
      {
        name: 'Custom Monogram Scarf & Jar',
        customDetails: 'Initials: M.I. • Lavender & Saffron',
        qty: 1,
      },
    ],
    courier: 'Delhivery Surface',
    awb: 'DL-883920194',
    pickupWindow: 'Today 4:00 PM - 7:00 PM',
    driverName: 'Satish (Delhivery Fleet)',
  },
  {
    orderId: 'DN-1032',
    customerName: 'Kabir Sengupta',
    phone: '+91 98455 33221',
    address: 'Flat 12, Palm Meadows, Whitefield',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560066',
    date: 'Yesterday, 04:15 PM',
    amount: 999,
    paymentMethod: 'Razorpay UPI',
    paymentStatus: 'PAID (Verified)',
    status: 'in_transit',
    statusBadge: 'IN TRANSIT',
    items: [
      {
        name: 'Terracotta Ribbed Knit Beanie',
        customDetails: 'Color: Rust Terracotta • Adult Fit',
        qty: 1,
      },
    ],
    courier: 'BlueDart Apex Air',
    awb: 'BD-449102931',
    pickupWindow: 'Picked up yesterday 6:30 PM',
    driverName: 'BlueDart Air Cargo Hub',
  },
];
